[[tls.certificates]]
  certFile = "/etc/certs/local.fr.crt"
  keyFile = "/etc/certs/local.fr.key"

[tls.stores]
  [tls.stores.default]
    [tls.stores.default.defaultCertificate]
      certFile = "/etc/certs/local.fr.crt"
      keyFile  = "/etc/certs/local.fr.key"
